### ISSUE TITLE
[New Project] aibtcdev

### ISSUE THREAD

**Issue by whoabuddy** [crewAIInc/awesome-crewai#2]
## Project Details

![aibtcdev-avatar-250px](https://github.com/user-attachments/assets/a228f3ce-131a-43fd-b817-cd2b59243919)

**Project Name:**  
aibtcdev

**Description:**  
AI meets Bitcoin. Build DAOs, chat, explore, all on-chain instantly.

**Repository Link:**  
https://github.com/aibtcdev

**Category:**  
Integrations

**Author:**  
@aibtcdev

**Impact or Use Case (Optional):**  
We developed a web interface that allows people to create and run crews that can interact with the [Stacks blockchain](https://www.stacks.co/). Agents have their own wallets and can function autonomously.

Users can [log into our app](https://sprint.aibtc.dev) with a Stacks wallet like [Leather](https://leather.io) or [Xverse](https://xverse.app) and:
- interact with crews using a chat-style interface
- run configured crews on a cron-style schedule
- create and manage DAOs deployed by agents
- get on-chain wallet, transaction, and smart contract info

**Additional Notes (Optional):**  
We are a working group that [meets every Thursday](https://evt.to/emamdeggw) and anyone is welcome to attend!

To learn more or follow along you can [follow us on X](https://x.com/aibtcdev), [join our Discord server](https://discord.gg/Z59Z3FNbEX), or [visit our main website](https://aibtc.dev) which links to all of our resources.

![aibtcdev-primary-logo-black-wide-1000px](https://github.com/user-attachments/assets/8aa7147f-7b6d-4eab-8a58-21cfcb300313)

**Comment by tonykipkemboi** [comment]
@whoabuddy thanks for your contribution. To make sure we don't deviate from the main motivation for creating this repo, I added some extra context to the readme file on the criteria. We'd love to keep it strictly for one-off projects by devs. If the project is much more developed (like yours), I believe we need another surface to highlight your offering. We currently have an ecosystem page but might be a little too early to add you there as well. I am going to create another repo to highlight products/companies using CrewAI to make sure we separate it from one-off projects.

**Comment by whoabuddy** [comment]
Awesome thanks! We love CrewAI and have been evolving with all of the releases since the 0.11.x days.

Amazing to see how far things have come and appreciate any exposure. Also happy to come and talk about our use cases and application sometime if interested!

**Comment by tonykipkemboi** [comment]
Hi @whoabuddy feel free to create a PR for the same in this dedicated "powered by CrewAI repo"
https://github.com/crewAIInc/companies-powered-by-crewai
